import {TWord} from '../../storage/words/words.types';

export type TStartDBChunk = {
  file: string;
  data: TWord[];
};

export const startDBChunks: TStartDBChunk[] = [
  {file: 'abstract-ideas-1.json', data: require('./abstract-ideas-1.json')},
  {file: 'abstract-ideas-2.json', data: require('./abstract-ideas-2.json')},
  {file: 'abstract-ideas-3.json', data: require('./abstract-ideas-3.json')},
  {file: 'abstract-ideas-4.json', data: require('./abstract-ideas-4.json')},
  {file: 'abstract-ideas-5.json', data: require('./abstract-ideas-5.json')},
  {file: 'abstract-ideas-6.json', data: require('./abstract-ideas-6.json')},
  {file: 'abstract-ideas-7.json', data: require('./abstract-ideas-7.json')},
  {file: 'abstract-ideas-8.json', data: require('./abstract-ideas-8.json')},
  {file: 'abstract-ideas-9.json', data: require('./abstract-ideas-9.json')},
  {file: 'abstract-ideas-10.json', data: require('./abstract-ideas-10.json')},
  {file: 'abstract-ideas-11.json', data: require('./abstract-ideas-11.json')},
  {file: 'abstract-ideas-12.json', data: require('./abstract-ideas-12.json')},
  {file: 'abstract-ideas-13.json', data: require('./abstract-ideas-13.json')},
  {file: 'abstract-ideas-14.json', data: require('./abstract-ideas-14.json')},
  {file: 'abstract-ideas-15.json', data: require('./abstract-ideas-15.json')},
  {file: 'abstract-ideas-16.json', data: require('./abstract-ideas-16.json')},
  {file: 'abstract-ideas-17.json', data: require('./abstract-ideas-17.json')},
  {file: 'abstract-ideas-18.json', data: require('./abstract-ideas-18.json')},
  {file: 'abstract-ideas-19.json', data: require('./abstract-ideas-19.json')},
  {file: 'abstract-ideas-20.json', data: require('./abstract-ideas-20.json')},
  {file: 'abstract-ideas-21.json', data: require('./abstract-ideas-21.json')},
  {file: 'abstract-ideas-22.json', data: require('./abstract-ideas-22.json')},
  {file: 'abstract-ideas-23.json', data: require('./abstract-ideas-23.json')},
  {file: 'abstract-ideas-24.json', data: require('./abstract-ideas-24.json')},
  {file: 'abstract-ideas-25.json', data: require('./abstract-ideas-25.json')},
  {file: 'abstract-ideas-26.json', data: require('./abstract-ideas-26.json')},
  {file: 'abstract-ideas-27.json', data: require('./abstract-ideas-27.json')},
  {file: 'abstract-ideas-28.json', data: require('./abstract-ideas-28.json')},
  {file: 'abstract-ideas-29.json', data: require('./abstract-ideas-29.json')},
  {file: 'abstract-ideas-30.json', data: require('./abstract-ideas-30.json')},
  {file: 'abstract-ideas-31.json', data: require('./abstract-ideas-31.json')},
  {file: 'abstract-ideas-32.json', data: require('./abstract-ideas-32.json')},
  {file: 'abstract-ideas-33.json', data: require('./abstract-ideas-33.json')},
  {file: 'abstract-ideas-34.json', data: require('./abstract-ideas-34.json')},
  {file: 'abstract-ideas-35.json', data: require('./abstract-ideas-35.json')},
  {file: 'abstract-ideas-36.json', data: require('./abstract-ideas-36.json')},
  {file: 'abstract-ideas-37.json', data: require('./abstract-ideas-37.json')},
  {file: 'abstract-ideas-38.json', data: require('./abstract-ideas-38.json')},
  {file: 'abstract-ideas-39.json', data: require('./abstract-ideas-39.json')},
  {file: 'abstract-ideas-40.json', data: require('./abstract-ideas-40.json')},
  {file: 'abstract-ideas-41.json', data: require('./abstract-ideas-41.json')},
  {file: 'abstract-ideas-42.json', data: require('./abstract-ideas-42.json')},
  {file: 'abstract-ideas-43.json', data: require('./abstract-ideas-43.json')},
  {file: 'abstract-ideas-44.json', data: require('./abstract-ideas-44.json')},
  {file: 'abstract-ideas-45.json', data: require('./abstract-ideas-45.json')},
  {file: 'abstract-ideas-46.json', data: require('./abstract-ideas-46.json')},
  {file: 'abstract-ideas-47.json', data: require('./abstract-ideas-47.json')},
  {file: 'abstract-ideas-48.json', data: require('./abstract-ideas-48.json')},
  {file: 'abstract-ideas-49.json', data: require('./abstract-ideas-49.json')},
  {file: 'abstract-ideas-50.json', data: require('./abstract-ideas-50.json')},
  {file: 'abstract-ideas-51.json', data: require('./abstract-ideas-51.json')},
  {file: 'abstract-ideas-52.json', data: require('./abstract-ideas-52.json')},
  {file: 'abstract-ideas-53.json', data: require('./abstract-ideas-53.json')},
  {file: 'abstract-ideas-54.json', data: require('./abstract-ideas-54.json')},
  {file: 'abstract-ideas-55.json', data: require('./abstract-ideas-55.json')},
  {file: 'abstract-ideas-56.json', data: require('./abstract-ideas-56.json')},
  {file: 'abstract-ideas-57.json', data: require('./abstract-ideas-57.json')},
  {file: 'abstract-ideas-58.json', data: require('./abstract-ideas-58.json')},
  {file: 'abstract-ideas-59.json', data: require('./abstract-ideas-59.json')},
  {file: 'abstract-ideas-60.json', data: require('./abstract-ideas-60.json')},
  {file: 'abstract-ideas-61.json', data: require('./abstract-ideas-61.json')},
  {file: 'abstract-ideas-62.json', data: require('./abstract-ideas-62.json')},
  {file: 'abstract-ideas-63.json', data: require('./abstract-ideas-63.json')},
  {file: 'abstract-ideas-64.json', data: require('./abstract-ideas-64.json')},
  {file: 'actions-movement-1.json', data: require('./actions-movement-1.json')},
  {file: 'actions-movement-2.json', data: require('./actions-movement-2.json')},
  {file: 'actions-movement-3.json', data: require('./actions-movement-3.json')},
  {file: 'actions-movement-4.json', data: require('./actions-movement-4.json')},
  {file: 'actions-movement-5.json', data: require('./actions-movement-5.json')},
  {file: 'actions-movement-6.json', data: require('./actions-movement-6.json')},
  {file: 'actions-movement-7.json', data: require('./actions-movement-7.json')},
  {file: 'actions-movement-8.json', data: require('./actions-movement-8.json')},
  {file: 'actions-movement-9.json', data: require('./actions-movement-9.json')},
  {
    file: 'actions-movement-10.json',
    data: require('./actions-movement-10.json'),
  },
  {
    file: 'actions-movement-11.json',
    data: require('./actions-movement-11.json'),
  },
  {
    file: 'actions-movement-12.json',
    data: require('./actions-movement-12.json'),
  },
  {
    file: 'actions-movement-13.json',
    data: require('./actions-movement-13.json'),
  },
  {
    file: 'actions-movement-14.json',
    data: require('./actions-movement-14.json'),
  },
  {
    file: 'actions-movement-15.json',
    data: require('./actions-movement-15.json'),
  },
  {
    file: 'actions-movement-16.json',
    data: require('./actions-movement-16.json'),
  },
  {
    file: 'actions-movement-17.json',
    data: require('./actions-movement-17.json'),
  },
  {
    file: 'actions-movement-18.json',
    data: require('./actions-movement-18.json'),
  },
  {
    file: 'actions-movement-19.json',
    data: require('./actions-movement-19.json'),
  },
  {
    file: 'actions-movement-20.json',
    data: require('./actions-movement-20.json'),
  },
  {
    file: 'actions-movement-21.json',
    data: require('./actions-movement-21.json'),
  },
  {
    file: 'actions-movement-22.json',
    data: require('./actions-movement-22.json'),
  },
  {
    file: 'actions-movement-23.json',
    data: require('./actions-movement-23.json'),
  },
  {
    file: 'actions-movement-24.json',
    data: require('./actions-movement-24.json'),
  },
  {
    file: 'actions-movement-25.json',
    data: require('./actions-movement-25.json'),
  },
  {
    file: 'actions-movement-26.json',
    data: require('./actions-movement-26.json'),
  },
  {
    file: 'actions-movement-27.json',
    data: require('./actions-movement-27.json'),
  },
  {
    file: 'actions-movement-28.json',
    data: require('./actions-movement-28.json'),
  },
  {
    file: 'actions-movement-29.json',
    data: require('./actions-movement-29.json'),
  },
  {
    file: 'actions-movement-30.json',
    data: require('./actions-movement-30.json'),
  },
  {
    file: 'actions-movement-31.json',
    data: require('./actions-movement-31.json'),
  },
  {
    file: 'actions-movement-32.json',
    data: require('./actions-movement-32.json'),
  },
  {
    file: 'actions-movement-33.json',
    data: require('./actions-movement-33.json'),
  },
  {
    file: 'actions-movement-34.json',
    data: require('./actions-movement-34.json'),
  },
  {
    file: 'actions-movement-35.json',
    data: require('./actions-movement-35.json'),
  },
  {
    file: 'actions-movement-36.json',
    data: require('./actions-movement-36.json'),
  },
  {
    file: 'actions-movement-37.json',
    data: require('./actions-movement-37.json'),
  },
  {
    file: 'actions-movement-38.json',
    data: require('./actions-movement-38.json'),
  },
  {
    file: 'actions-movement-39.json',
    data: require('./actions-movement-39.json'),
  },
  {
    file: 'actions-movement-40.json',
    data: require('./actions-movement-40.json'),
  },
  {
    file: 'actions-movement-41.json',
    data: require('./actions-movement-41.json'),
  },
  {
    file: 'actions-movement-42.json',
    data: require('./actions-movement-42.json'),
  },
  {file: 'body-health-1.json', data: require('./body-health-1.json')},
  {file: 'body-health-2.json', data: require('./body-health-2.json')},
  {file: 'body-health-3.json', data: require('./body-health-3.json')},
  {file: 'body-health-4.json', data: require('./body-health-4.json')},
  {file: 'body-health-5.json', data: require('./body-health-5.json')},
  {
    file: 'culture-entertainment-1.json',
    data: require('./culture-entertainment-1.json'),
  },
  {
    file: 'culture-entertainment-2.json',
    data: require('./culture-entertainment-2.json'),
  },
  {
    file: 'culture-entertainment-3.json',
    data: require('./culture-entertainment-3.json'),
  },
  {
    file: 'feelings-qualities-1.json',
    data: require('./feelings-qualities-1.json'),
  },
  {
    file: 'feelings-qualities-2.json',
    data: require('./feelings-qualities-2.json'),
  },
  {
    file: 'feelings-qualities-3.json',
    data: require('./feelings-qualities-3.json'),
  },
  {
    file: 'feelings-qualities-4.json',
    data: require('./feelings-qualities-4.json'),
  },
  {file: 'food-drink-1.json', data: require('./food-drink-1.json')},
  {file: 'food-drink-2.json', data: require('./food-drink-2.json')},
  {file: 'food-drink-3.json', data: require('./food-drink-3.json')},
  {file: 'food-drink-4.json', data: require('./food-drink-4.json')},
  {file: 'grammar-function-1.json', data: require('./grammar-function-1.json')},
  {file: 'grammar-function-2.json', data: require('./grammar-function-2.json')},
  {file: 'grammar-function-3.json', data: require('./grammar-function-3.json')},
  {file: 'grammar-function-4.json', data: require('./grammar-function-4.json')},
  {file: 'grammar-function-5.json', data: require('./grammar-function-5.json')},
  {file: 'grammar-function-6.json', data: require('./grammar-function-6.json')},
  {file: 'grammar-function-7.json', data: require('./grammar-function-7.json')},
  {file: 'grammar-function-8.json', data: require('./grammar-function-8.json')},
  {file: 'grammar-function-9.json', data: require('./grammar-function-9.json')},
  {
    file: 'grammar-function-10.json',
    data: require('./grammar-function-10.json'),
  },
  {file: 'home-daily-life-1.json', data: require('./home-daily-life-1.json')},
  {file: 'home-daily-life-2.json', data: require('./home-daily-life-2.json')},
  {file: 'home-daily-life-3.json', data: require('./home-daily-life-3.json')},
  {
    file: 'nature-environment-1.json',
    data: require('./nature-environment-1.json'),
  },
  {
    file: 'nature-environment-2.json',
    data: require('./nature-environment-2.json'),
  },
  {
    file: 'nature-environment-3.json',
    data: require('./nature-environment-3.json'),
  },
  {file: 'people-family-1.json', data: require('./people-family-1.json')},
  {file: 'people-family-2.json', data: require('./people-family-2.json')},
  {file: 'people-family-3.json', data: require('./people-family-3.json')},
  {
    file: 'school-work-business-1.json',
    data: require('./school-work-business-1.json'),
  },
  {
    file: 'school-work-business-2.json',
    data: require('./school-work-business-2.json'),
  },
  {
    file: 'school-work-business-3.json',
    data: require('./school-work-business-3.json'),
  },
  {
    file: 'society-law-politics-1.json',
    data: require('./society-law-politics-1.json'),
  },
  {
    file: 'society-law-politics-2.json',
    data: require('./society-law-politics-2.json'),
  },
  {file: 'technology-media-1.json', data: require('./technology-media-1.json')},
  {file: 'technology-media-2.json', data: require('./technology-media-2.json')},
  {file: 'technology-media-3.json', data: require('./technology-media-3.json')},
  {file: 'time-numbers-1.json', data: require('./time-numbers-1.json')},
  {file: 'time-numbers-2.json', data: require('./time-numbers-2.json')},
  {file: 'time-numbers-3.json', data: require('./time-numbers-3.json')},
  {file: 'time-numbers-4.json', data: require('./time-numbers-4.json')},
  {file: 'travel-transport-1.json', data: require('./travel-transport-1.json')},
  {file: 'travel-transport-2.json', data: require('./travel-transport-2.json')},
  {file: 'travel-transport-3.json', data: require('./travel-transport-3.json')},
];
